# Generated by Django 3.2.9 on 2021-11-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_start_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='kickborad',
            new_name='kickboard',
        ),
    ]
